# Site settings
title: Chair of Informatics
email: ftninformatika@uns.ac.rs
description: Chair of Informatics, Faculty of Technical Sciences, University of Novi Sad
baseurl: "/informatika/" # the subpath of your site, e.g. /blog/
url: "http://unsftn.github.io" # the base hostname & protocol for your site
twitter_username: ftninformatika
github_username:  ftninformatika

collections:
  news:
    output: true
    permalink: /news/:path/
  events:
    output: true
    permalink: /events/:path/
  courses:
    output: true
    permalink: :path/
  publications:
    output: true
    permalink: /publications/:path/
  faculty:
    output: true
    permalink: /:path/


defaults:
  - scope:
      path: "courses"
      type: courses
    values: 
      layout: page

# Build settings
markdown: kramdown

